### ISSUE TITLE
publish job failing 

### ISSUE THREAD

**Issue by Nikolara97** [aaronparker/intune-backup-template#4]
Hi aaron, all the sudden publish job (convert markdown to HTML start failing). Here is error can you please support me with this one, thanks :)

<img width="724" alt="image" src="https://user-images.githubusercontent.com/121571467/236137808-9b0ecbdc-ceab-409e-b2cc-e1ee6e330036.png">

**Comment by aaronparker** [comment]
I'm not sure what the issue is - I've tested with earlier versions `md-to-pdf` than the latest `5.2.4`. It does work locally on macOS, but is failing with the same issue in my tenant.

It is working OK on GitHub, so this only appears to be an issue on Azure DevOps, so perhaps something with the DevOps runners.

**Comment by Nikolara97** [comment]
So what would be your suggestion, just to wait or? :D
    On Thursday, May 4, 2023 at 11:37:13 AM GMT+2, Aaron Parker ***@***.***> wrote:  
 
 


I'm not sure what the issue is - I've tested with earlier versions md-to-pdf than the latest 5.2.4. It does work locally on macOS, but is failing with the same issue in my tenant.

It is working OK on GitHub, so this only appears to be an issue on Azure DevOps, so perhaps something with the DevOps runners.

**Comment by aaronparker** [comment]
I've logged an issue here https://github.com/simonhaenisch/md-to-pdf/issues/198, but I'm not 100% convinced this is an md-to-pdf issue.

You could try to change the pipeline to run on Windows or configure the pipeline to continue on fail and see whether the HTML is actually produced or not.

**Comment by aaronparker** [comment]
Take another copy of the pipeline, I've change values on a couple of properties - `failOnStderr: false`

**Comment by Nikolara97** [comment]
First part with Windows was not working, but once I added to both tasks convert-to-html and convert-to-pdf (continueOnError: true) I am still getting same error, but pipeline is generating both artifacts (Html/PDF)...
    On Friday, May 5, 2023 at 10:05:10 AM GMT+2, Aaron Parker ***@***.***> wrote:  
 
 


Take another copy of the pipeline, I've change values on a couple of properties - failOnStderr: false
