### ISSUE TITLE
403 Error in backup stage

### ISSUE THREAD

**Issue by Shivang-Patel-BlueLeaf** [aaronparker/intune-backup-template#6]
Hello.

I'm trying to set up the IntuneCD automation in github. I've imported the github from the preview and I've set up all the client secrets and such, but whenever I run the Backup Intune config workflow, I get an error during the Backup Intune configuration stage:

![image](https://github.com/aaronparker/intune-backup-template/assets/143013323/4c83062a-bdb6-454b-a706-e66074aa663e)

I redid all of the secrets, remaking the GPG key and PAT, I remade the client secret in App Registration and I revised all of the API permissions to exactly what the original IntuneCD required. Incase it helps, my API permissions are currently:

![image](https://github.com/aaronparker/intune-backup-template/assets/143013323/439eb8bc-1cb3-4edb-906d-c7a1c13b7139)

All have received admin consent. When I run the 4 lines of code from the https://stealthpuppy.com/automate-intune-documentation-github/ page, I also get the same error during the first line of code. 

Please let me know if there are any fixes.

Thank you,
Shivang Patel

**Comment by aaronparker** [comment]
It looks like a permissions issue. Do all permissions list admin consent granted?

![image](https://github.com/aaronparker/intune-backup-template/assets/8227455/19c1c80c-9f05-482b-914b-cd0739cba77e)

It would be worth checking the issue list on the IntuneCD repo https://github.com/almenscorner/IntuneCD/issues?q=is%3Aissue+403

**Comment by Shivang-Patel-BlueLeaf** [comment]
From what I can tell it's not a permissions issue. All of the permissions were listed with admin consent and I have the same permissions as all of yours, so I'm not sure why it doesn't work. My current fix is excluding Remote Assistance Partners by adding on "--exclude RemoteAssistancePartner" onto the Intune-startbackup command in the code. 

This is an issue from IntuneCD, not the automation part, so I'll investigate more there. Thanks for the help!
